version: "3.9"
services:
  api:
    build: .
    dns:
      - 8.8.8.8
    container_name: ai_tutor_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: ai_tutor_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ai_tutor_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: 